config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :skills do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show] do
    resources :reviews, only: [:create, :new, :show]
  end
  resources :bookings, only: :index
  resources :users, only: [:show, :edit] do
    resources :skills, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  has_many :reviews, dependent: :destroy

  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :address, presence: true

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :skills

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, allow_blank: false, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookings
  has_many :reviews, through: :bookings

  validates :title, presence: true
  validates :title, uniqueness: { scope: :user }
  validates :price_per_hour, presence: true
  validates :earliest_available, presence: true
  validates :latest_available, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :skills, dependent: :destroy
  has_many :bookings
  has_many :reviews, through: :bookings

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  def after_sign_in_path_for(user)
    skills_path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).where(user: current_user).order(created_at: :desc)
  end

  def new
    @booking = Booking.new
    @skill = Skill.find(params[:skill_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user = current_user
    @skill = Skill.find(params[:skill_id])
    @booking.skill = @skill
    if @booking.save
      redirect_to bookings_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def show
    @user = current_user
    @booking = Booking.find(params[:id])
    @review = Review.new
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :total_price, :address, :contact_info)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = Booking.find(params[:booking_id])
    authorize @review
    if @review.save
      redirect_to skill_path(@review.booking.skill)
    else
      render :new
    end
  end

  def show
    authorize @review
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :destroy]
  after_action :verify_policy_scoped, only: [:index]

  def index
    if params[:query].present?
      @skills = policy_scope(Skill).where("title ILIKE ?", "%#{params[:query]}%").order(created_at: :desc)
    else
      @skills = policy_scope(Skill).all.order(created_at: :desc)
    end
  end

  def new
    @skill = Skill.new
    authorize @skill
  end

  def create
    @skill = Skill.new(skill_params)
    @user = current_user
    @skill.user = @user
    authorize @skill
    if @skill.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
    authorize @skill
  end

  def destroy
    @skill.destroy
    redirect_to root_path
  end

  private

  def set_skill
    @skill = Skill.find(params[:id])
  end

  def skill_params
    params.require(:skill).permit(:category_id, :title, :price_per_hour, :earliest_available, :latest_available)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]

  def show
    authorize @user
  end

  def edit
    @skill = Skill.new
    authorize @user
  end

  def create
    @skill = Skill.new(skill_params)
    @user = current_user
    @skill.user = @user
    authorize @skill
    if @skill.save
      redirect_to @user
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container text-center my-3">
  <h4>My Bookings</h4>
  <% @bookings.each do |booking| %>
    <div class="card-skill">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path booking.skill.category.image %>')">
        <%= booking.skill.category.title %>
      </div>
      <div class="card-skill-infos">
        <div class="col">
          <h2><%= booking.skill.title %></h2>
          <p><%= booking.address %></p>
          <p><%= booking.start_time.strftime("%I:%M:%S %p") %></p>
        </div>
        <div class="personal">
          <%= image_tag booking.skill.user.picture, class:"card-skill-user avatar-bordered"%>
          <p><%= booking.skill.user.first_name %></p>
          <h2 class="card-skill-pricing"><i class="fas fa-euro-sign"></i><%= booking.skill.price_per_hour %></h2>
        </div>
      </div>
      <%= link_to "Write a Review", booking_path(booking) %>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= link_to skills_path do %>
    <i class="fas fa-chevron-circle-left"> Back </i>
  <% end %>
  <div class="view-card my-3">
    <%= image_tag @skill.user.picture, class: "avatar-bordered", alt: "avatar-bordered" %>
    <h3>Make a booking with <%= @skill.user.first_name %></h3>
    <p><strong>Available Times:</strong></p>
    <%= @skill.earliest_available.strftime("%I:%M:%S %p") %> -- <%= @skill.latest_available.strftime("%I:%M:%S %p") %>
    <div class="booking-form mt-3">
      <%= simple_form_for [@skill, @booking] do |f| %>
        <%= f.input :address %>
        <%= f.input :start_time %>
        <%= f.input :end_time %>
        <%= f.input :contact_info %>
        <%= f.submit "Book Now!", class:"btn btn-flat" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <%= simple_form_for [@booking, @review] do |r| %>
    <%= r.input :content %>
    <%= r.input :rating %>
    <%= r.submit "Add Review", class: "btn btn-flat" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="main-container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [@booking, @review] do |r| %>
    <%= r.input :content %>
    <%= r.input :rating %>
    <%= r.submit "add a review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
  
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-tools">~ Fix My Sh*t</i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= link_to skills_path do %> <%= image_tag "lifesaver.png", class:"logo w-25" %>
      <h5>Fix My Sh*t!</h5>
    <% end %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", skills_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Profile", user_path(current_user) ,class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/skills/index.html.erb
<div class="welcome">
  <h4>Hello, <%= current_user.first_name %> ! What do you need fixed today?</h4>
</div>
<div class="container text-center my-3">
  <!-- break -->
  <%= form_tag skills_path, method: :get do %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Select a skill"
  %>
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    <% end %>
  </div>
  <!-- Skills Listings -->
  <% @skills.each do |skill| %>
    <div class="card-skill">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path skill.category.image %>')">
        <%= skill.category.title %>
      </div>
      <div class="card-skill-infos">
        <div class="col">
          <h4><%= skill.title %></h4>
          <h6><%= skill.user.first_name %></h6>
          <p><i class="fas fa-euro-sign"></i><%= skill.price_per_hour %>/per hour</p>
          <p><%= skill.user.location %></p>
        </div>
        <%= image_tag skill.user.picture, class:"card-skill-user avatar-bordered"%>
        <%= link_to "See More", skill_path(skill), class:"button-more" %>
      </div>
    </div>
  <% end %>
</div>

app/views/skills/new.html.erb
<%#= simple_form_for @skill do |f| %>
  <%#= f.association :category %>
  <%#= f.input :title  %>
  <%#= f.input :earliest_available  %>
  <%#= f.input :latest_available  %>
  <%#= f.submit "save", class: "btn btn-ghost"  %>
  <%# end %>

app/views/skills/show.html.erb
<div class="container">
  <div class="card-category my-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path @skill.category.image %>')">
    <%= @skill.category.title %>
  </div>
  <%= link_to skills_path do %>
    <i class="fas fa-chevron-circle-left"> Back</i>
  <% end %>
  <div class="user-info">
    <div class="col-8 offset-2 text-center">
      <h4><%= @skill.title %></h4>
      <%= image_tag @skill.user.picture, class:"card-skill-user avatar-bordered w-50 h-50 my-3"%>
      <p><strong><em><%= @skill.user.first_name %></em></strong></p>
      <p><%= link_to "View Profile", user_path(@skill.user.id) %></p>
      <h5>Price:</h5>
      <p><i class="fas fa-euro-sign"></i><%= @skill.price_per_hour %>/per hour</p>
      <h5>Availability:</h5>
      <p><%= @skill.earliest_available.strftime("%I:%M:%S %p") %> -- <%= @skill.latest_available.strftime("%I:%M:%S %p") %></p>
      <h5>Location:</h5>
      <p><%= @skill.user.location %></p>
      <!-- Reviews Secton Here -->
      <div class="review-box">
        <h4>Reviews</h4>
        <% @skill.reviews.each do |review| %>
          <% review.rating.times do %>⭐️
          <% end %>
          <p><%= review.content %></p>
        <% end %>
      </div>
      <%= link_to "Make a Booking!", new_skill_booking_path(@skill), class:"btn btn-flat p-2 my-3" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container my-3 p-3">
  <%= simple_form_for(current_user) do |user| %>
    <%= user.input :picture, class:"card-skill-user avatar-bordered w-25 h-25 my-3"%>
    <%= user.input :first_name %>
    <%= user.input :last_name %>
    <%= user.input :contact_info%>
    <%= user.submit "Save", class: "btn btn-primary" %>
  <% end %>
  <div class="card-skill-add my-3 p-3">
    <h3>Add a Skill!</h3>
    <%= simple_form_for @skill do |skill| %>
      <%= skill.association :category %>
      <%= skill.input :price_per_hour %>
      <%= skill.input :title, placeholder: "please describe (e.g. plumber)" %>
      <%= skill.input :earliest_available %>
      <%= skill.input :latest_available %>
      <%= skill.submit "Add Skill", class: "btn btn-primary mb-3" %>
    <% end %>
  </div>
  <%= link_to user_path do %>
    <i class="fas fa-chevron-circle-left ml-3"> Back</i>
  <% end %>
</div>

app/views/users/show.html.erb
  <%#= link_to skills_path do %>
  <!-- <i class="fas fa-chevron-circle-left ml-3"> Back</i> -->
  <%# end %>
  <div class="container text-center">
    <%= image_tag current_user.picture, class:"card-skill-user avatar-bordered w-50 h-50 my-3" %>
    <h1>Hi! I'm <%= current_user.first_name %></h1>
    <%= link_to "Edit Profile", edit_user_path %>
    <p><em>Location: <%= current_user.location %></em></p>
    <div class="btn btn-flat my-3 w-75">My Skills</div>
    <%= link_to edit_user_path do %>
      <i class="fas fa-plus mb-3 text-primary"> Add a skill!</i>
    <% end %>
    <% current_user.skills.each do |skill| %>
      <p><%= skill.title %></p>
    <% end %>
  </div>
</div>